services:
  - type: web
    name: escuadron-jeager
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
    startCommand: gunicorn EscuadronJeager01.wsgi
