services:
  - type: web
    name: escuadron-jeager
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn EscuadronJeager01.wsgi"
    preDeployCommand: "python manage.py migrate"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: EscuadronJeager01.settings
      - key: DATABASE_URL
        sync: false  # Render la buscar√° en el entorno
    plan: free
    autoDeploy: true
